# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x10inventoryPackage\">\n\x08PartInfo\x12\x0e\n\x06partId\x18\x01 \x01(\t\x12\x10\n\x08partName\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"$\n\x11\x43heckPartsRequest\x12\x0f\n\x07partIds\x18\x01 \x03(\t\"C\n\x12\x43heckPartsResponse\x12-\n\tpartsInfo\x18\x01 \x03(\x0b\x32\x1a.inventoryPackage.PartInfo\"\xb6\x01\n\x13ReservePartsRequest\x12\x15\n\rreservationId\x18\x01 \x01(\t\x12Q\n\x0epartsToReserve\x18\x02 \x03(\x0b\x32\x39.inventoryPackage.ReservePartsRequest.PartsToReserveEntry\x1a\x35\n\x13PartsToReserveEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"8\n\x14ReservePartsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x17GetRequiredPartsRequest\x12\x16\n\x0erepairTypeName\x18\x01 \x01(\t\"I\n\x18GetRequiredPartsResponse\x12-\n\tpartsInfo\x18\x01 \x03(\x0b\x32\x1a.inventoryPackage.PartInfo\"\xa6\x01\n\x18ManageStockLevelsRequest\x12T\n\rpartsToUpdate\x18\x01 \x03(\x0b\x32=.inventoryPackage.ManageStockLevelsRequest.PartsToUpdateEntry\x1a\x34\n\x12PartsToUpdateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"=\n\x19ManageStockLevelsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xaf\x03\n\x10InventoryService\x12\x63\n\x16\x43heckPartsAvailability\x12#.inventoryPackage.CheckPartsRequest\x1a$.inventoryPackage.CheckPartsResponse\x12]\n\x0cReserveParts\x12%.inventoryPackage.ReservePartsRequest\x1a&.inventoryPackage.ReservePartsResponse\x12i\n\x10GetRequiredParts\x12).inventoryPackage.GetRequiredPartsRequest\x1a*.inventoryPackage.GetRequiredPartsResponse\x12l\n\x11ManageStockLevels\x12*.inventoryPackage.ManageStockLevelsRequest\x1a+.inventoryPackage.ManageStockLevelsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVEPARTSREQUEST_PARTSTORESERVEENTRY']._loaded_options = None
  _globals['_RESERVEPARTSREQUEST_PARTSTORESERVEENTRY']._serialized_options = b'8\001'
  _globals['_MANAGESTOCKLEVELSREQUEST_PARTSTOUPDATEENTRY']._loaded_options = None
  _globals['_MANAGESTOCKLEVELSREQUEST_PARTSTOUPDATEENTRY']._serialized_options = b'8\001'
  _globals['_PARTINFO']._serialized_start=37
  _globals['_PARTINFO']._serialized_end=99
  _globals['_CHECKPARTSREQUEST']._serialized_start=101
  _globals['_CHECKPARTSREQUEST']._serialized_end=137
  _globals['_CHECKPARTSRESPONSE']._serialized_start=139
  _globals['_CHECKPARTSRESPONSE']._serialized_end=206
  _globals['_RESERVEPARTSREQUEST']._serialized_start=209
  _globals['_RESERVEPARTSREQUEST']._serialized_end=391
  _globals['_RESERVEPARTSREQUEST_PARTSTORESERVEENTRY']._serialized_start=338
  _globals['_RESERVEPARTSREQUEST_PARTSTORESERVEENTRY']._serialized_end=391
  _globals['_RESERVEPARTSRESPONSE']._serialized_start=393
  _globals['_RESERVEPARTSRESPONSE']._serialized_end=449
  _globals['_GETREQUIREDPARTSREQUEST']._serialized_start=451
  _globals['_GETREQUIREDPARTSREQUEST']._serialized_end=500
  _globals['_GETREQUIREDPARTSRESPONSE']._serialized_start=502
  _globals['_GETREQUIREDPARTSRESPONSE']._serialized_end=575
  _globals['_MANAGESTOCKLEVELSREQUEST']._serialized_start=578
  _globals['_MANAGESTOCKLEVELSREQUEST']._serialized_end=744
  _globals['_MANAGESTOCKLEVELSREQUEST_PARTSTOUPDATEENTRY']._serialized_start=692
  _globals['_MANAGESTOCKLEVELSREQUEST_PARTSTOUPDATEENTRY']._serialized_end=744
  _globals['_MANAGESTOCKLEVELSRESPONSE']._serialized_start=746
  _globals['_MANAGESTOCKLEVELSRESPONSE']._serialized_end=807
  _globals['_INVENTORYSERVICE']._serialized_start=810
  _globals['_INVENTORYSERVICE']._serialized_end=1241
# @@protoc_insertion_point(module_scope)
