# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reservation_pb2 as reservation__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reservation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReservation = channel.unary_unary(
                '/reservationPackage.ReservationService/CreateReservation',
                request_serializer=reservation__pb2.CreateReservationRequest.SerializeToString,
                response_deserializer=reservation__pb2.ReservationResponse.FromString,
                _registered_method=True)
        self.GetReservation = channel.unary_unary(
                '/reservationPackage.ReservationService/GetReservation',
                request_serializer=reservation__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=reservation__pb2.ReservationResponse.FromString,
                _registered_method=True)
        self.GetReservations = channel.unary_unary(
                '/reservationPackage.ReservationService/GetReservations',
                request_serializer=reservation__pb2.GetReservationsRequest.SerializeToString,
                response_deserializer=reservation__pb2.ReservationsResponse.FromString,
                _registered_method=True)
        self.UpdateReservation = channel.unary_unary(
                '/reservationPackage.ReservationService/UpdateReservation',
                request_serializer=reservation__pb2.UpdateReservationRequest.SerializeToString,
                response_deserializer=reservation__pb2.ReservationResponse.FromString,
                _registered_method=True)
        self.DeleteReservation = channel.unary_unary(
                '/reservationPackage.ReservationService/DeleteReservation',
                request_serializer=reservation__pb2.DeleteReservationRequest.SerializeToString,
                response_deserializer=reservation__pb2.EmptyResponse.FromString,
                _registered_method=True)


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReservation,
                    request_deserializer=reservation__pb2.CreateReservationRequest.FromString,
                    response_serializer=reservation__pb2.ReservationResponse.SerializeToString,
            ),
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=reservation__pb2.GetReservationRequest.FromString,
                    response_serializer=reservation__pb2.ReservationResponse.SerializeToString,
            ),
            'GetReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservations,
                    request_deserializer=reservation__pb2.GetReservationsRequest.FromString,
                    response_serializer=reservation__pb2.ReservationsResponse.SerializeToString,
            ),
            'UpdateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReservation,
                    request_deserializer=reservation__pb2.UpdateReservationRequest.FromString,
                    response_serializer=reservation__pb2.ReservationResponse.SerializeToString,
            ),
            'DeleteReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReservation,
                    request_deserializer=reservation__pb2.DeleteReservationRequest.FromString,
                    response_serializer=reservation__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reservationPackage.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reservationPackage.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservationPackage.ReservationService/CreateReservation',
            reservation__pb2.CreateReservationRequest.SerializeToString,
            reservation__pb2.ReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservationPackage.ReservationService/GetReservation',
            reservation__pb2.GetReservationRequest.SerializeToString,
            reservation__pb2.ReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservationPackage.ReservationService/GetReservations',
            reservation__pb2.GetReservationsRequest.SerializeToString,
            reservation__pb2.ReservationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservationPackage.ReservationService/UpdateReservation',
            reservation__pb2.UpdateReservationRequest.SerializeToString,
            reservation__pb2.ReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservationPackage.ReservationService/DeleteReservation',
            reservation__pb2.DeleteReservationRequest.SerializeToString,
            reservation__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
